from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import matplotlib.pyplot as plt
import pandas as pd
from tarif_python import tarif
from grafik_python import Grafik

class BesinlerGUI(QtWidgets.QStackedWidget):
    #Arayüz Tasarımı
#################################################################################################################################
    def setup(self):
        self.setObjectName("page_besin")
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 40, 110, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn1_levrek = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1_levrek.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn1_levrek.setFont(font)
        self.btn1_levrek.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn1_levrek.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn1_levrek.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn1_levrek.setStyleSheet("")
        self.btn1_levrek.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/levrek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn1_levrek.setIcon(icon3)
        self.btn1_levrek.setIconSize(QtCore.QSize(84, 60))
        self.btn1_levrek.setFlat(True)
        self.btn1_levrek.setObjectName("btn1_levrek")
        self.verticalLayout.addWidget(self.btn1_levrek, 0, QtCore.Qt.AlignHCenter)
        self.btn2_ton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2_ton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn2_ton.sizePolicy().hasHeightForWidth())
        self.btn2_ton.setSizePolicy(sizePolicy)
        self.btn2_ton.setMaximumSize(QtCore.QSize(16777215, 51))
        self.btn2_ton.setBaseSize(QtCore.QSize(1, 1))
        self.btn2_ton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn2_ton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/ton balığı.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn2_ton.setIcon(icon4)
        self.btn2_ton.setIconSize(QtCore.QSize(84, 60))
        self.btn2_ton.setDefault(False)
        self.btn2_ton.setFlat(True)
        self.btn2_ton.setObjectName("btn2_ton")
        self.verticalLayout.addWidget(self.btn2_ton)
        self.btn3_aycicek_yagi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3_aycicek_yagi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn3_aycicek_yagi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn3_aycicek_yagi.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/aycicek_yagi.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btn3_aycicek_yagi.setIcon(icon5)
        self.btn3_aycicek_yagi.setIconSize(QtCore.QSize(64, 48))
        self.btn3_aycicek_yagi.setAutoDefault(False)
        self.btn3_aycicek_yagi.setDefault(False)
        self.btn3_aycicek_yagi.setFlat(True)
        self.btn3_aycicek_yagi.setObjectName("btn3_aycicek_yagi")
        self.verticalLayout.addWidget(self.btn3_aycicek_yagi)
        self.btn4_zeytin_yagi = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4_zeytin_yagi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn4_zeytin_yagi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn4_zeytin_yagi.setToolTipDuration(-1)
        self.btn4_zeytin_yagi.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/zeytinyagi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn4_zeytin_yagi.setIcon(icon6)
        self.btn4_zeytin_yagi.setIconSize(QtCore.QSize(48, 48))
        self.btn4_zeytin_yagi.setFlat(True)
        self.btn4_zeytin_yagi.setObjectName("btn4_zeytin_yagi")
        self.verticalLayout.addWidget(self.btn4_zeytin_yagi)
        self.btn5_bezelye = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5_bezelye.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn5_bezelye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn5_bezelye.setToolTipDuration(-1)
        self.btn5_bezelye.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/bezelye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn5_bezelye.setIcon(icon7)
        self.btn5_bezelye.setIconSize(QtCore.QSize(48, 48))
        self.btn5_bezelye.setFlat(True)
        self.btn5_bezelye.setObjectName("btn5_bezelye")
        self.verticalLayout.addWidget(self.btn5_bezelye)
        self.btn6_zeytin_siyah = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6_zeytin_siyah.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn6_zeytin_siyah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn6_zeytin_siyah.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/zeytin_siyah.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btn6_zeytin_siyah.setIcon(icon8)
        self.btn6_zeytin_siyah.setIconSize(QtCore.QSize(84, 48))
        self.btn6_zeytin_siyah.setFlat(True)
        self.btn6_zeytin_siyah.setObjectName("btn6_zeytin_siyah")
        self.verticalLayout.addWidget(self.btn6_zeytin_siyah)
        self.btn7_zeytin_yesil = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7_zeytin_yesil.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn7_zeytin_yesil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn7_zeytin_yesil.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/zeytin_yesil.ico"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btn7_zeytin_yesil.setIcon(icon9)
        self.btn7_zeytin_yesil.setIconSize(QtCore.QSize(84, 48))
        self.btn7_zeytin_yesil.setFlat(True)
        self.btn7_zeytin_yesil.setObjectName("btn7_zeytin_yesil")
        self.verticalLayout.addWidget(self.btn7_zeytin_yesil)
        self.btn8_ekmek_bugday = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8_ekmek_bugday.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn8_ekmek_bugday.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn8_ekmek_bugday.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/whole-wheat-bread.png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn8_ekmek_bugday.setIcon(icon10)
        self.btn8_ekmek_bugday.setIconSize(QtCore.QSize(96, 48))
        self.btn8_ekmek_bugday.setFlat(True)
        self.btn8_ekmek_bugday.setObjectName("btn8_ekmek_bugday")
        self.verticalLayout.addWidget(self.btn8_ekmek_bugday)
        self.btn9_ekmek_beyaz = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9_ekmek_beyaz.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn9_ekmek_beyaz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn9_ekmek_beyaz.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/ekmek.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn9_ekmek_beyaz.setIcon(icon11)
        self.btn9_ekmek_beyaz.setIconSize(QtCore.QSize(48, 64))
        self.btn9_ekmek_beyaz.setFlat(True)
        self.btn9_ekmek_beyaz.setObjectName("btn9_ekmek_beyaz")
        self.verticalLayout.addWidget(self.btn9_ekmek_beyaz)
        self.btn10_makarna = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn10_makarna.setMaximumSize(QtCore.QSize(16777215, 60))
        self.btn10_makarna.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn10_makarna.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn10_makarna.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/makarna.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn10_makarna.setIcon(icon12)
        self.btn10_makarna.setIconSize(QtCore.QSize(48, 48))
        self.btn10_makarna.setFlat(True)
        self.btn10_makarna.setObjectName("btn10_makarna")
        self.verticalLayout.addWidget(self.btn10_makarna)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 40, 91, 511))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(4, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn11_adacayi = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn11_adacayi.setMaximumSize(QtCore.QSize(16777215, 64))
        self.btn11_adacayi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn11_adacayi.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/adaçayı.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn11_adacayi.setIcon(icon13)
        self.btn11_adacayi.setIconSize(QtCore.QSize(64, 48))
        self.btn11_adacayi.setFlat(True)
        self.btn11_adacayi.setObjectName("btn11_adacayi")
        self.verticalLayout_2.addWidget(self.btn11_adacayi)
        self.btn12_tereyagi = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn12_tereyagi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn12_tereyagi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn12_tereyagi.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/butter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn12_tereyagi.setIcon(icon14)
        self.btn12_tereyagi.setIconSize(QtCore.QSize(48, 48))
        self.btn12_tereyagi.setFlat(True)
        self.btn12_tereyagi.setObjectName("btn12_tereyagi")
        self.verticalLayout_2.addWidget(self.btn12_tereyagi)
        self.btn13_kahve = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn13_kahve.setMaximumSize(QtCore.QSize(16777215, 45))
        self.btn13_kahve.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn13_kahve.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/coffee-cup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn13_kahve.setIcon(icon15)
        self.btn13_kahve.setIconSize(QtCore.QSize(48, 48))
        self.btn13_kahve.setFlat(True)
        self.btn13_kahve.setObjectName("btn13_kahve")
        self.verticalLayout_2.addWidget(self.btn13_kahve)
        self.btn14_dana_eti = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn14_dana_eti.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn14_dana_eti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn14_dana_eti.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/et.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn14_dana_eti.setIcon(icon16)
        self.btn14_dana_eti.setIconSize(QtCore.QSize(48, 48))
        self.btn14_dana_eti.setFlat(True)
        self.btn14_dana_eti.setObjectName("btn14_dana_eti")
        self.verticalLayout_2.addWidget(self.btn14_dana_eti)
        self.btn15_ay_cekirdegi = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn15_ay_cekirdegi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn15_ay_cekirdegi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn15_ay_cekirdegi.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/ay çekirdeği 2.png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn15_ay_cekirdegi.setIcon(icon17)
        self.btn15_ay_cekirdegi.setIconSize(QtCore.QSize(48, 48))
        self.btn15_ay_cekirdegi.setFlat(True)
        self.btn15_ay_cekirdegi.setObjectName("btn15_ay_cekirdegi")
        self.verticalLayout_2.addWidget(self.btn15_ay_cekirdegi)
        self.btn16_badem = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn16_badem.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn16_badem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn16_badem.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/badem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn16_badem.setIcon(icon18)
        self.btn16_badem.setIconSize(QtCore.QSize(48, 48))
        self.btn16_badem.setFlat(True)
        self.btn16_badem.setObjectName("btn16_badem")
        self.verticalLayout_2.addWidget(self.btn16_badem)
        self.btn17_findik = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn17_findik.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn17_findik.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn17_findik.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/fındık.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn17_findik.setIcon(icon19)
        self.btn17_findik.setIconSize(QtCore.QSize(48, 48))
        self.btn17_findik.setFlat(True)
        self.btn17_findik.setObjectName("btn17_findik")
        self.verticalLayout_2.addWidget(self.btn17_findik)
        self.btn18_kuru_fasulye = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn18_kuru_fasulye.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn18_kuru_fasulye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn18_kuru_fasulye.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/fasulye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn18_kuru_fasulye.setIcon(icon20)
        self.btn18_kuru_fasulye.setIconSize(QtCore.QSize(48, 48))
        self.btn18_kuru_fasulye.setFlat(True)
        self.btn18_kuru_fasulye.setObjectName("btn18_kuru_fasulye")
        self.verticalLayout_2.addWidget(self.btn18_kuru_fasulye)
        self.btn19_mercimek = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn19_mercimek.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn19_mercimek.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn19_mercimek.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/mercimek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn19_mercimek.setIcon(icon21)
        self.btn19_mercimek.setIconSize(QtCore.QSize(48, 48))
        self.btn19_mercimek.setFlat(True)
        self.btn19_mercimek.setObjectName("btn19_mercimek")
        self.verticalLayout_2.addWidget(self.btn19_mercimek)
        self.btn20_nohut = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn20_nohut.setMaximumSize(QtCore.QSize(16777215, 64))
        self.btn20_nohut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn20_nohut.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/nohut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn20_nohut.setIcon(icon22)
        self.btn20_nohut.setIconSize(QtCore.QSize(48, 64))
        self.btn20_nohut.setFlat(True)
        self.btn20_nohut.setObjectName("btn20_nohut")
        self.verticalLayout_2.addWidget(self.btn20_nohut)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(240, 40, 91, 511))
        self.gridLayoutWidget_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn21_tavuk = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn21_tavuk.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn21_tavuk.setFont(font)
        self.btn21_tavuk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn21_tavuk.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn21_tavuk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn21_tavuk.setStyleSheet("")
        self.btn21_tavuk.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/tavuk.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn21_tavuk.setIcon(icon23)
        self.btn21_tavuk.setIconSize(QtCore.QSize(48, 48))
        self.btn21_tavuk.setFlat(True)
        self.btn21_tavuk.setObjectName("btn21_tavuk")
        self.verticalLayout_3.addWidget(self.btn21_tavuk)
        self.btn22_cilek = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn22_cilek.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn22_cilek.sizePolicy().hasHeightForWidth())
        self.btn22_cilek.setSizePolicy(sizePolicy)
        self.btn22_cilek.setMaximumSize(QtCore.QSize(16777215, 51))
        self.btn22_cilek.setBaseSize(QtCore.QSize(1, 1))
        self.btn22_cilek.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn22_cilek.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/çilek.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn22_cilek.setIcon(icon24)
        self.btn22_cilek.setIconSize(QtCore.QSize(48, 48))
        self.btn22_cilek.setDefault(False)
        self.btn22_cilek.setFlat(True)
        self.btn22_cilek.setObjectName("btn22_cilek")
        self.verticalLayout_3.addWidget(self.btn22_cilek)
        self.btn23_elma = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn23_elma.setMaximumSize(QtCore.QSize(16777215, 48))
        self.btn23_elma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn23_elma.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/elma.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn23_elma.setIcon(icon25)
        self.btn23_elma.setIconSize(QtCore.QSize(48, 82))
        self.btn23_elma.setAutoDefault(False)
        self.btn23_elma.setDefault(False)
        self.btn23_elma.setFlat(True)
        self.btn23_elma.setObjectName("btn23_elma")
        self.verticalLayout_3.addWidget(self.btn23_elma)
        self.btn24_kayisi = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn24_kayisi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn24_kayisi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn24_kayisi.setToolTipDuration(-1)
        self.btn24_kayisi.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/kayısı.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn24_kayisi.setIcon(icon26)
        self.btn24_kayisi.setIconSize(QtCore.QSize(48, 48))
        self.btn24_kayisi.setFlat(True)
        self.btn24_kayisi.setObjectName("btn24_kayisi")
        self.verticalLayout_3.addWidget(self.btn24_kayisi)
        self.btn25_limon = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn25_limon.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn25_limon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn25_limon.setToolTipDuration(-1)
        self.btn25_limon.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/limon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn25_limon.setIcon(icon27)
        self.btn25_limon.setIconSize(QtCore.QSize(48, 48))
        self.btn25_limon.setFlat(True)
        self.btn25_limon.setObjectName("btn25_limon")
        self.verticalLayout_3.addWidget(self.btn25_limon)
        self.btn26_muz = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn26_muz.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn26_muz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn26_muz.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/muz.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn26_muz.setIcon(icon28)
        self.btn26_muz.setIconSize(QtCore.QSize(48, 48))
        self.btn26_muz.setFlat(True)
        self.btn26_muz.setObjectName("btn26_muz")
        self.verticalLayout_3.addWidget(self.btn26_muz)
        self.btn27_nar = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn27_nar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn27_nar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn27_nar.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/nar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn27_nar.setIcon(icon29)
        self.btn27_nar.setIconSize(QtCore.QSize(48, 48))
        self.btn27_nar.setFlat(True)
        self.btn27_nar.setObjectName("btn27_nar")
        self.verticalLayout_3.addWidget(self.btn27_nar)
        self.btn28_bogurtlen = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn28_bogurtlen.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn28_bogurtlen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn28_bogurtlen.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/böğürtlrn2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn28_bogurtlen.setIcon(icon30)
        self.btn28_bogurtlen.setIconSize(QtCore.QSize(48, 48))
        self.btn28_bogurtlen.setFlat(True)
        self.btn28_bogurtlen.setObjectName("btn28_bogurtlen")
        self.verticalLayout_3.addWidget(self.btn28_bogurtlen)
        self.btn29_portakal = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn29_portakal.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn29_portakal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn29_portakal.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/portakal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn29_portakal.setIcon(icon31)
        self.btn29_portakal.setIconSize(QtCore.QSize(48, 48))
        self.btn29_portakal.setFlat(True)
        self.btn29_portakal.setObjectName("btn29_portakal")
        self.verticalLayout_3.addWidget(self.btn29_portakal)
        self.btn30_beyaz_peynir = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btn30_beyaz_peynir.setMaximumSize(QtCore.QSize(16777215, 60))
        self.btn30_beyaz_peynir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn30_beyaz_peynir.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/peynir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn30_beyaz_peynir.setIcon(icon32)
        self.btn30_beyaz_peynir.setIconSize(QtCore.QSize(64, 64))
        self.btn30_beyaz_peynir.setFlat(True)
        self.btn30_beyaz_peynir.setObjectName("btn30_beyaz_peynir")
        self.verticalLayout_3.addWidget(self.btn30_beyaz_peynir)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(330, 40, 101, 511))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn31_hurma = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn31_hurma.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn31_hurma.setFont(font)
        self.btn31_hurma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn31_hurma.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn31_hurma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn31_hurma.setStyleSheet("")
        self.btn31_hurma.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/hurma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn31_hurma.setIcon(icon33)
        self.btn31_hurma.setIconSize(QtCore.QSize(48, 48))
        self.btn31_hurma.setFlat(True)
        self.btn31_hurma.setObjectName("btn31_hurma")
        self.verticalLayout_6.addWidget(self.btn31_hurma)
        self.btn32_domates = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn32_domates.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn32_domates.sizePolicy().hasHeightForWidth())
        self.btn32_domates.setSizePolicy(sizePolicy)
        self.btn32_domates.setMaximumSize(QtCore.QSize(16777215, 51))
        self.btn32_domates.setBaseSize(QtCore.QSize(1, 1))
        self.btn32_domates.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn32_domates.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/tomato.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn32_domates.setIcon(icon34)
        self.btn32_domates.setIconSize(QtCore.QSize(48, 48))
        self.btn32_domates.setDefault(False)
        self.btn32_domates.setFlat(True)
        self.btn32_domates.setObjectName("btn32_domates")
        self.verticalLayout_6.addWidget(self.btn32_domates)
        self.btn33_havuc = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn33_havuc.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn33_havuc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn33_havuc.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/havuç.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn33_havuc.setIcon(icon35)
        self.btn33_havuc.setIconSize(QtCore.QSize(48, 48))
        self.btn33_havuc.setAutoDefault(False)
        self.btn33_havuc.setDefault(False)
        self.btn33_havuc.setFlat(True)
        self.btn33_havuc.setObjectName("btn33_havuc")
        self.verticalLayout_6.addWidget(self.btn33_havuc)
        self.btn34_salatalik = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn34_salatalik.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn34_salatalik.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn34_salatalik.setToolTipDuration(-1)
        self.btn34_salatalik.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/hıyar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn34_salatalik.setIcon(icon36)
        self.btn34_salatalik.setIconSize(QtCore.QSize(48, 48))
        self.btn34_salatalik.setFlat(True)
        self.btn34_salatalik.setObjectName("btn34_salatalik")
        self.verticalLayout_6.addWidget(self.btn34_salatalik)
        self.btn35_ispanak = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn35_ispanak.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn35_ispanak.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn35_ispanak.setToolTipDuration(-1)
        self.btn35_ispanak.setText("")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/ıspanak.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn35_ispanak.setIcon(icon37)
        self.btn35_ispanak.setIconSize(QtCore.QSize(48, 48))
        self.btn35_ispanak.setFlat(True)
        self.btn35_ispanak.setObjectName("btn35_ispanak")
        self.verticalLayout_6.addWidget(self.btn35_ispanak)
        self.btn36_kabak = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn36_kabak.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn36_kabak.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn36_kabak.setText("")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/kabak.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn36_kabak.setIcon(icon38)
        self.btn36_kabak.setIconSize(QtCore.QSize(48, 48))
        self.btn36_kabak.setFlat(True)
        self.btn36_kabak.setObjectName("btn36_kabak")
        self.verticalLayout_6.addWidget(self.btn36_kabak)
        self.btn37_brokoli = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn37_brokoli.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn37_brokoli.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn37_brokoli.setText("")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/brokoli.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn37_brokoli.setIcon(icon39)
        self.btn37_brokoli.setIconSize(QtCore.QSize(48, 48))
        self.btn37_brokoli.setFlat(True)
        self.btn37_brokoli.setObjectName("btn37_brokoli")
        self.verticalLayout_6.addWidget(self.btn37_brokoli)
        self.btn38_karnabahar = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn38_karnabahar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn38_karnabahar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn38_karnabahar.setText("")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/karnabahar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn38_karnabahar.setIcon(icon40)
        self.btn38_karnabahar.setIconSize(QtCore.QSize(48, 48))
        self.btn38_karnabahar.setFlat(True)
        self.btn38_karnabahar.setObjectName("btn38_karnabahar")
        self.verticalLayout_6.addWidget(self.btn38_karnabahar)
        self.btn39_kereviz = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn39_kereviz.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn39_kereviz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn39_kereviz.setText("")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/kereviz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn39_kereviz.setIcon(icon41)
        self.btn39_kereviz.setIconSize(QtCore.QSize(48, 48))
        self.btn39_kereviz.setFlat(True)
        self.btn39_kereviz.setObjectName("btn39_kereviz")
        self.verticalLayout_6.addWidget(self.btn39_kereviz)
        self.btn40_kara_lahana = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btn40_kara_lahana.setMaximumSize(QtCore.QSize(16777215, 60))
        self.btn40_kara_lahana.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn40_kara_lahana.setText("")
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/kara lahana.png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn40_kara_lahana.setIcon(icon42)
        self.btn40_kara_lahana.setIconSize(QtCore.QSize(48, 48))
        self.btn40_kara_lahana.setFlat(True)
        self.btn40_kara_lahana.setObjectName("btn40_kara_lahana")
        self.verticalLayout_6.addWidget(self.btn40_kara_lahana)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(430, 40, 91, 511))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn41_marul = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn41_marul.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn41_marul.setFont(font)
        self.btn41_marul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn41_marul.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn41_marul.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn41_marul.setStyleSheet("")
        self.btn41_marul.setText("")
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/marul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn41_marul.setIcon(icon43)
        self.btn41_marul.setIconSize(QtCore.QSize(48, 48))
        self.btn41_marul.setFlat(True)
        self.btn41_marul.setObjectName("btn41_marul")
        self.verticalLayout_5.addWidget(self.btn41_marul)
        self.btn42_maydanoz = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn42_maydanoz.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn42_maydanoz.sizePolicy().hasHeightForWidth())
        self.btn42_maydanoz.setSizePolicy(sizePolicy)
        self.btn42_maydanoz.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn42_maydanoz.setBaseSize(QtCore.QSize(1, 1))
        self.btn42_maydanoz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn42_maydanoz.setText("")
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/maydanoz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn42_maydanoz.setIcon(icon44)
        self.btn42_maydanoz.setIconSize(QtCore.QSize(48, 48))
        self.btn42_maydanoz.setDefault(False)
        self.btn42_maydanoz.setFlat(True)
        self.btn42_maydanoz.setObjectName("btn42_maydanoz")
        self.verticalLayout_5.addWidget(self.btn42_maydanoz)
        self.btn43_misir = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn43_misir.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn43_misir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn43_misir.setText("")
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/mısır.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn43_misir.setIcon(icon45)
        self.btn43_misir.setIconSize(QtCore.QSize(48, 48))
        self.btn43_misir.setAutoDefault(False)
        self.btn43_misir.setDefault(False)
        self.btn43_misir.setFlat(True)
        self.btn43_misir.setObjectName("btn43_misir")
        self.verticalLayout_5.addWidget(self.btn43_misir)
        self.btn44_patates = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn44_patates.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn44_patates.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn44_patates.setToolTipDuration(-1)
        self.btn44_patates.setText("")
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/patates.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn44_patates.setIcon(icon46)
        self.btn44_patates.setIconSize(QtCore.QSize(48, 48))
        self.btn44_patates.setFlat(True)
        self.btn44_patates.setObjectName("btn44_patates")
        self.verticalLayout_5.addWidget(self.btn44_patates)
        self.btn45_patlican = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn45_patlican.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn45_patlican.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn45_patlican.setText("")
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/patlıcan.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn45_patlican.setIcon(icon47)
        self.btn45_patlican.setIconSize(QtCore.QSize(48, 48))
        self.btn45_patlican.setFlat(True)
        self.btn45_patlican.setObjectName("btn45_patlican")
        self.verticalLayout_5.addWidget(self.btn45_patlican)
        self.btn46_kuru_sogan = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn46_kuru_sogan.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn46_kuru_sogan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn46_kuru_sogan.setToolTipDuration(-1)
        self.btn46_kuru_sogan.setText("")
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/soğan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn46_kuru_sogan.setIcon(icon48)
        self.btn46_kuru_sogan.setIconSize(QtCore.QSize(48, 48))
        self.btn46_kuru_sogan.setFlat(True)
        self.btn46_kuru_sogan.setObjectName("btn46_kuru_sogan")
        self.verticalLayout_5.addWidget(self.btn46_kuru_sogan)
        self.btn47_salca = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn47_salca.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn47_salca.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn47_salca.setText("")
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/salça.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn47_salca.setIcon(icon49)
        self.btn47_salca.setIconSize(QtCore.QSize(48, 48))
        self.btn47_salca.setFlat(True)
        self.btn47_salca.setObjectName("btn47_salca")
        self.verticalLayout_5.addWidget(self.btn47_salca)
        self.btn48_sut = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn48_sut.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn48_sut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn48_sut.setText("")
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/süt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn48_sut.setIcon(icon50)
        self.btn48_sut.setIconSize(QtCore.QSize(48, 48))
        self.btn48_sut.setFlat(True)
        self.btn48_sut.setObjectName("btn48_sut")
        self.verticalLayout_5.addWidget(self.btn48_sut)
        self.btn49_yogurt = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn49_yogurt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn49_yogurt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn49_yogurt.setText("")
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/yogurt(bi bu çeşit var).png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn49_yogurt.setIcon(icon51)
        self.btn49_yogurt.setIconSize(QtCore.QSize(48, 48))
        self.btn49_yogurt.setFlat(True)
        self.btn49_yogurt.setObjectName("btn49_yogurt")
        self.verticalLayout_5.addWidget(self.btn49_yogurt)
        self.btn50_bal = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btn50_bal.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn50_bal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn50_bal.setText("")
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/bal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn50_bal.setIcon(icon52)
        self.btn50_bal.setIconSize(QtCore.QSize(48, 48))
        self.btn50_bal.setFlat(True)
        self.btn50_bal.setObjectName("btn50_bal")
        self.verticalLayout_5.addWidget(self.btn50_bal)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(520, 40, 111, 511))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gridLayoutWidget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn51_cikolata = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn51_cikolata.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn51_cikolata.setFont(font)
        self.btn51_cikolata.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn51_cikolata.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn51_cikolata.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn51_cikolata.setStyleSheet("")
        self.btn51_cikolata.setText("")
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/çikolata.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn51_cikolata.setIcon(icon53)
        self.btn51_cikolata.setIconSize(QtCore.QSize(48, 48))
        self.btn51_cikolata.setFlat(True)
        self.btn51_cikolata.setObjectName("btn51_cikolata")
        self.verticalLayout_4.addWidget(self.btn51_cikolata)
        self.btn52_pekmez = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn52_pekmez.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn52_pekmez.sizePolicy().hasHeightForWidth())
        self.btn52_pekmez.setSizePolicy(sizePolicy)
        self.btn52_pekmez.setMaximumSize(QtCore.QSize(16777215, 51))
        self.btn52_pekmez.setBaseSize(QtCore.QSize(1, 1))
        self.btn52_pekmez.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn52_pekmez.setText("")
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/pekmez(emin değilim).png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn52_pekmez.setIcon(icon54)
        self.btn52_pekmez.setIconSize(QtCore.QSize(48, 48))
        self.btn52_pekmez.setDefault(False)
        self.btn52_pekmez.setFlat(True)
        self.btn52_pekmez.setObjectName("btn52_pekmez")
        self.verticalLayout_4.addWidget(self.btn52_pekmez)
        self.btn53_seker = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn53_seker.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn53_seker.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn53_seker.setText("")
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/şeker.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn53_seker.setIcon(icon55)
        self.btn53_seker.setIconSize(QtCore.QSize(48, 48))
        self.btn53_seker.setAutoDefault(False)
        self.btn53_seker.setDefault(False)
        self.btn53_seker.setFlat(True)
        self.btn53_seker.setObjectName("btn53_seker")
        self.verticalLayout_4.addWidget(self.btn53_seker)
        self.btn54_tahin = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn54_tahin.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn54_tahin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn54_tahin.setToolTipDuration(-1)
        self.btn54_tahin.setText("")
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/tahin (emin değilim).png"), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btn54_tahin.setIcon(icon56)
        self.btn54_tahin.setIconSize(QtCore.QSize(48, 48))
        self.btn54_tahin.setFlat(True)
        self.btn54_tahin.setObjectName("btn54_tahin")
        self.verticalLayout_4.addWidget(self.btn54_tahin)
        self.btn55_bugday = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn55_bugday.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn55_bugday.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn55_bugday.setToolTipDuration(-1)
        self.btn55_bugday.setText("")
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/buğday.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn55_bugday.setIcon(icon57)
        self.btn55_bugday.setIconSize(QtCore.QSize(48, 48))
        self.btn55_bugday.setFlat(True)
        self.btn55_bugday.setObjectName("btn55_bugday")
        self.verticalLayout_4.addWidget(self.btn55_bugday)
        self.btn56_bulgur = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn56_bulgur.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn56_bulgur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn56_bulgur.setText("")
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/bulgur.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn56_bulgur.setIcon(icon58)
        self.btn56_bulgur.setIconSize(QtCore.QSize(84, 48))
        self.btn56_bulgur.setFlat(True)
        self.btn56_bulgur.setObjectName("btn56_bulgur")
        self.verticalLayout_4.addWidget(self.btn56_bulgur)
        self.btn57_pirinc = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn57_pirinc.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn57_pirinc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn57_pirinc.setText("")
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/pirinç.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn57_pirinc.setIcon(icon59)
        self.btn57_pirinc.setIconSize(QtCore.QSize(48, 48))
        self.btn57_pirinc.setFlat(True)
        self.btn57_pirinc.setObjectName("btn57_pirinc")
        self.verticalLayout_4.addWidget(self.btn57_pirinc)
        self.btn58_yulaf_unu = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn58_yulaf_unu.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn58_yulaf_unu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn58_yulaf_unu.setText("")
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/yulaf unu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn58_yulaf_unu.setIcon(icon60)
        self.btn58_yulaf_unu.setIconSize(QtCore.QSize(48, 48))
        self.btn58_yulaf_unu.setFlat(True)
        self.btn58_yulaf_unu.setObjectName("btn58_yulaf_unu")
        self.verticalLayout_4.addWidget(self.btn58_yulaf_unu)
        self.btn59_yumurta = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn59_yumurta.setMaximumSize(QtCore.QSize(16777215, 50))
        self.btn59_yumurta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn59_yumurta.setText("")
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap(":/besinler/besinler_icons/yumurta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn59_yumurta.setIcon(icon61)
        self.btn59_yumurta.setIconSize(QtCore.QSize(48, 48))
        self.btn59_yumurta.setFlat(True)
        self.btn59_yumurta.setObjectName("btn59_yumurta")
        self.verticalLayout_4.addWidget(self.btn59_yumurta)
        self.label_besin_degerleri = QtWidgets.QLabel(self)
        self.label_besin_degerleri.setGeometry(QtCore.QRect(0, 0, 610, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_besin_degerleri.setFont(font)
        self.label_besin_degerleri.setMouseTracking(False)
        self.label_besin_degerleri.setAutoFillBackground(False)
        self.label_besin_degerleri.setStyleSheet("border-color: rgb(85, 0, 255);\n"
                                                 "background-color: rgb(48,123,172);\n""\n"
                                                 "color:rgb(242,240,240);""")

        self.label_besin_degerleri.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_besin_degerleri.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_besin_degerleri.setLineWidth(0)
        self.label_besin_degerleri.setIndent(20)
        self.label_besin_degerleri.setObjectName("label_besin_degerleri")
#################################################################################################################################

        self.tarif_page = tarif()
        self.grafik_page = Grafik()

        #Besin butonları
        self.buttons = [
                self.btn1_levrek,self.btn2_ton,self.btn3_aycicek_yagi,self.btn4_zeytin_yagi,self.btn5_bezelye,
                self.btn6_zeytin_siyah,self.btn7_zeytin_yesil,self.btn8_ekmek_bugday,self.btn9_ekmek_beyaz,
                self.btn10_makarna,self.btn11_adacayi,self.btn12_tereyagi,self.btn13_kahve,self.btn14_dana_eti,
                self.btn15_ay_cekirdegi,self.btn16_badem,self.btn17_findik,self.btn18_kuru_fasulye,self.btn19_mercimek,
                self.btn20_nohut,self.btn21_tavuk,self.btn22_cilek,self.btn23_elma,self.btn24_kayisi,self.btn25_limon,
                self.btn26_muz,self.btn27_nar,self.btn28_bogurtlen,self.btn29_portakal,self.btn30_beyaz_peynir,
                self.btn31_hurma,self.btn32_domates,self.btn33_havuc,self.btn34_salatalik,self.btn35_ispanak,
                self.btn36_kabak,self.btn37_brokoli,self.btn38_karnabahar,self.btn39_kereviz,self.btn40_kara_lahana,
                self.btn41_marul,self.btn42_maydanoz,self.btn43_misir,self.btn44_patates,self.btn45_patlican,self.btn46_kuru_sogan,
                self.btn47_salca,self.btn48_sut,self.btn49_yogurt,self.btn50_bal,self.btn51_cikolata,self.btn52_pekmez,
                self.btn53_seker,self.btn54_tahin,self.btn55_bugday,self.btn56_bulgur,self.btn57_pirinc,self.btn58_yulaf_unu,self.btn59_yumurta,
                ]

        #Besin butonları sinyalleri
        for i in range(59):
            self.buttons[i].clicked.connect(lambda ch,i = i: self.besin_degerleri_goster(buton_indeksi = i))

        return self


    @QtCore.pyqtSlot()
    def besin_degerleri_goster(self, buton_indeksi):
        """Besinin değerlerini pasta grafiği olarak göster"""
        # besin_degerleri.csv dosyası DataFrame olarak okunur
        besin = pd.read_csv('.\\csv_files\\besin_degerleri.csv', names=['besin', 'protein', 'karbonhidrat', 'yag', 'kalori'])
        # for döngüsünde kullanılacak ve indeks bilgisini tutan count değişkeni ilklendirildi
        count = 0
        # besin dosyası içinde gezinerek pasta grafiklerini ekrana basar
        for i in besin.besin:
            if buton_indeksi == count:  #Tıklanılan buton indeksi ise besin değerlerini göster
                self.plot(count)        #plot() fonksiyonu çağrısı
                return
            count += 1  # indeks değerini 1 artır


    def plot(self,index):
        """Parametre ile alınan indekse göre tıklanan besinin değerlerini göster"""
        for i in range(59):
            if i == index:

                #{}.format ile string içerisinde değişken kullanıldı.(istenilen grafik indeksi)
                image = "background-image: url(:/grafik/icons/grafik/{}.png);".format(index)

                #Tıklanan grafiği göster
                self.grafik_page.ui.label_grafik_1.setStyleSheet(image)
                self.grafik_page.setFixedSize(550, 380)
                self.grafik_page.show()

    def retranslate(self):
        _translate = QtCore.QCoreApplication.translate

        self.btn1_levrek.setToolTip(_translate("main", "Levrek"))
        self.btn2_ton.setToolTip(_translate("main", "Ton Balığı"))
        self.btn3_aycicek_yagi.setToolTip(_translate("main", "Ayçiçek Yağı"))
        self.btn4_zeytin_yagi.setToolTip(_translate("main", "Zeytin Yağı"))
        self.btn5_bezelye.setToolTip(_translate("main", "Bezelye"))
        self.btn6_zeytin_siyah.setToolTip(_translate("main", "Zeytin(Siyah)"))
        self.btn7_zeytin_yesil.setToolTip(_translate("main", "Zeytin(Yeşil)"))
        self.btn8_ekmek_bugday.setToolTip(_translate("main", "Ekmek(Buğday)"))
        self.btn9_ekmek_beyaz.setToolTip(_translate("main", "Ekmek(Beyaz)"))
        self.btn10_makarna.setToolTip(_translate("main", "Makarna"))
        self.btn11_adacayi.setToolTip(_translate("main", "Ada Çayı"))
        self.btn12_tereyagi.setToolTip(_translate("main", "Tereyağı"))
        self.btn13_kahve.setToolTip(_translate("main", "Kahve"))
        self.btn14_dana_eti.setToolTip(_translate("main", "Dana Eti"))
        self.btn15_ay_cekirdegi.setToolTip(_translate("main", "Ay Çekirdeği"))
        self.btn16_badem.setToolTip(_translate("main", "Badem"))
        self.btn17_findik.setToolTip(_translate("main", "Fındık"))
        self.btn18_kuru_fasulye.setToolTip(_translate("main", "Kuru Fasulye"))
        self.btn19_mercimek.setToolTip(_translate("main", "Mercimek"))
        self.btn20_nohut.setToolTip(_translate("main", "Nohut"))
        self.btn21_tavuk.setToolTip(_translate("main", "Tavuk"))
        self.btn22_cilek.setToolTip(_translate("main", "Çilek"))
        self.btn23_elma.setToolTip(_translate("main", "Elma"))
        self.btn24_kayisi.setToolTip(_translate("main", "Kayısı"))
        self.btn25_limon.setToolTip(_translate("main", "Limon"))
        self.btn26_muz.setToolTip(_translate("main", "Muz"))
        self.btn27_nar.setToolTip(_translate("main", "Nar"))
        self.btn28_bogurtlen.setToolTip(_translate("main", "Böğürtlen"))
        self.btn29_portakal.setToolTip(_translate("main", "Portakal"))
        self.btn30_beyaz_peynir.setToolTip(_translate("main", "Beyaz Peynir"))
        self.btn31_hurma.setToolTip(_translate("main", "Hurma"))
        self.btn32_domates.setToolTip(_translate("main", "Domates"))
        self.btn33_havuc.setToolTip(_translate("main", "Havuç"))
        self.btn34_salatalik.setToolTip(_translate("main", "Salatalık"))
        self.btn35_ispanak.setToolTip(_translate("main", "Ispanak"))
        self.btn36_kabak.setToolTip(_translate("main", "Kabak"))
        self.btn37_brokoli.setToolTip(_translate("main", "Brokoli"))
        self.btn38_karnabahar.setToolTip(_translate("main", "Karnabahar"))
        self.btn39_kereviz.setToolTip(_translate("main", "Kereviz"))
        self.btn40_kara_lahana.setToolTip(_translate("main", "Kara Lahana"))
        self.btn41_marul.setToolTip(_translate("main", "Marul"))
        self.btn42_maydanoz.setToolTip(_translate("main", "Maydanoz"))
        self.btn43_misir.setToolTip(_translate("main", "Mısır"))
        self.btn44_patates.setToolTip(_translate("main", "Patates"))
        self.btn45_patlican.setToolTip(_translate("main", "Patlıcan"))
        self.btn46_kuru_sogan.setToolTip(_translate("main", "Kuru Soğan"))
        self.btn47_salca.setToolTip(_translate("main", "Salça"))
        self.btn48_sut.setToolTip(_translate("main", "İnek Sütü"))
        self.btn49_yogurt.setToolTip(_translate("main", "Yoğurt"))
        self.btn50_bal.setToolTip(_translate("main", "Bal"))
        self.btn51_cikolata.setToolTip(_translate("main", "Çikolata"))
        self.btn52_pekmez.setToolTip(_translate("main", "Pekmez"))
        self.btn53_seker.setToolTip(_translate("main", "Şeker"))
        self.btn54_tahin.setToolTip(_translate("main", "Tahin"))
        self.btn55_bugday.setToolTip(_translate("main", "Buğday"))
        self.btn56_bulgur.setToolTip(_translate("main", "Bulgur"))
        self.btn57_pirinc.setToolTip(_translate("main", "Pirinç"))
        self.btn58_yulaf_unu.setToolTip(_translate("main", "Yulaf Unu"))
        self.btn59_yumurta.setToolTip(_translate("main", "Yumurta"))
        self.label_besin_degerleri.setText(_translate("main", "Lütfen değerlerini öğrenmek istediğiniz besine tıklayınız"))
