# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/eyuph/Desktop/Python/Proje/grafik.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Grafik(object):
    def setupUi(self, Grafik):
        Grafik.setObjectName("Grafik")
        Grafik.resize(957, 458)
        Grafik.setMinimumSize(QtCore.QSize(510, 450))
        Grafik.setMaximumSize(QtCore.QSize(1000, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-ingredients-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Grafik.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Grafik)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 10, 861, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_grafik_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_grafik_1.setStyleSheet("")
        self.label_grafik_1.setText("")
        self.label_grafik_1.setObjectName("label_grafik_1")
        self.gridLayout.addWidget(self.label_grafik_1, 1, 0, 1, 1)
        self.label_grafik_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_grafik_2.setStyleSheet("")
        self.label_grafik_2.setText("")
        self.label_grafik_2.setObjectName("label_grafik_2")
        self.gridLayout.addWidget(self.label_grafik_2, 1, 1, 1, 1)
        self.label_grafik_yaz2 = QtWidgets.QLabel(Grafik)
        self.label_grafik_yaz2.setGeometry(QtCore.QRect(500, 360, 481, 20))
        self.label_grafik_yaz2.setText("")
        self.label_grafik_yaz2.setObjectName("label_grafik_yaz2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Grafik)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(60, 470, 861, 341))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_grafik_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_grafik_4.setStyleSheet("")
        self.label_grafik_4.setText("")
        self.label_grafik_4.setObjectName("label_grafik_4")
        self.gridLayout_2.addWidget(self.label_grafik_4, 0, 1, 1, 1)
        self.label_grafik_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_grafik_3.setStyleSheet("")
        self.label_grafik_3.setText("")
        self.label_grafik_3.setObjectName("label_grafik_3")
        self.gridLayout_2.addWidget(self.label_grafik_3, 0, 0, 1, 1)
        self.label_grafik_yaz3 = QtWidgets.QLabel(Grafik)
        self.label_grafik_yaz3.setGeometry(QtCore.QRect(10, 780, 451, 20))
        self.label_grafik_yaz3.setText("")
        self.label_grafik_yaz3.setObjectName("label_grafik_yaz3")
        self.label_grafik_yaz4 = QtWidgets.QLabel(Grafik)
        self.label_grafik_yaz4.setGeometry(QtCore.QRect(490, 780, 471, 16))
        self.label_grafik_yaz4.setText("")
        self.label_grafik_yaz4.setObjectName("label_grafik_yaz4")
        self.textEdit_grafik_yazi1 = QtWidgets.QTextEdit(Grafik)
        self.textEdit_grafik_yazi1.setGeometry(QtCore.QRect(60, 380, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_grafik_yazi1.setFont(font)
        self.textEdit_grafik_yazi1.setReadOnly(True)
        self.textEdit_grafik_yazi1.setObjectName("textEdit_grafik_yazi1")
        self.textEdit_grafik_yazi2 = QtWidgets.QTextEdit(Grafik)
        self.textEdit_grafik_yazi2.setEnabled(True)
        self.textEdit_grafik_yazi2.setGeometry(QtCore.QRect(510, 380, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_grafik_yazi2.setFont(font)
        self.textEdit_grafik_yazi2.setReadOnly(True)
        self.textEdit_grafik_yazi2.setObjectName("textEdit_grafik_yazi2")
        self.textEdit_grafik_yazi3 = QtWidgets.QTextEdit(Grafik)
        self.textEdit_grafik_yazi3.setGeometry(QtCore.QRect(60, 840, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_grafik_yazi3.setFont(font)
        self.textEdit_grafik_yazi3.setReadOnly(True)
        self.textEdit_grafik_yazi3.setObjectName("textEdit_grafik_yazi3")
        self.textEdit_grafik_yazi4 = QtWidgets.QTextEdit(Grafik)
        self.textEdit_grafik_yazi4.setGeometry(QtCore.QRect(510, 840, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_grafik_yazi4.setFont(font)
        self.textEdit_grafik_yazi4.setReadOnly(True)
        self.textEdit_grafik_yazi4.setObjectName("textEdit_grafik_yazi4")

        self.retranslateUi(Grafik)
        QtCore.QMetaObject.connectSlotsByName(Grafik)

    def retranslateUi(self, Grafik):
        _translate = QtCore.QCoreApplication.translate
        Grafik.setWindowTitle(_translate("Grafik", "Grafik Sayfası"))

import icons_rc
class Grafik(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Grafik()
        self.ui.setupUi(self)

    def closeEvent(self, event):
        self.clear()
    def clear(self):
        self.ui.label_grafik_1.setStyleSheet("")
        self.ui.label_grafik_2.setStyleSheet("")
        self.ui.label_grafik_3.setStyleSheet("")
        self.ui.label_grafik_4.setStyleSheet("")
        self.ui.textEdit_grafik_yazi1.clear()
        self.ui.textEdit_grafik_yazi2.clear()
        self.ui.textEdit_grafik_yazi3.clear()
        self.ui.textEdit_grafik_yazi4.clear()