from PyQt5.QtCore import Qt
from profile import Profile
from update_profile import updateProfile
from PyQt5 import QtCore, QtGui, QtWidgets

class ProfilimGUI(QtWidgets.QStackedWidget):
    profiles = []  # profiller listesi
    def setup(self):
        #Arayüz tasarımı
#################################################################################################################
        self.setObjectName("page_profilim")
        self.formWidget = QtWidgets.QWidget(self)
        self.formWidget.setGeometry(QtCore.QRect(0, 140, 391, 411))
        self.formWidget.setAutoFillBackground(False)
        self.formWidget.setObjectName("formWidget")
        self.label_name = QtWidgets.QLabel(self.formWidget)
        self.label_name.setEnabled(True)
        self.label_name.setGeometry(QtCore.QRect(10, 20, 160, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_age = QtWidgets.QLabel(self.formWidget)
        self.label_age.setGeometry(QtCore.QRect(10, 80, 160, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.label_kitle_indeks = QtWidgets.QLabel(self.formWidget)
        self.label_kitle_indeks.setGeometry(QtCore.QRect(10, 320, 200, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_kitle_indeks.setFont(font)
        self.label_kitle_indeks.setObjectName("label_kitle_indeks")
        self.label_kalori_ihtiyac = QtWidgets.QLabel(self.formWidget)
        self.label_kalori_ihtiyac.setGeometry(QtCore.QRect(10, 380, 250, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_kalori_ihtiyac.setFont(font)
        self.label_kalori_ihtiyac.setObjectName("label_kalori_ihtiyac")
        self.label_weight = QtWidgets.QLabel(self.formWidget)
        self.label_weight.setGeometry(QtCore.QRect(10, 140, 180, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_weight.setFont(font)
        self.label_weight.setObjectName("label_weight")
        self.label_boy = QtWidgets.QLabel(self.formWidget)
        self.label_boy.setGeometry(QtCore.QRect(10, 200, 160, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_boy.setFont(font)
        self.label_boy.setObjectName("label_boy")
        self.label_name_ = QtWidgets.QLabel(self.formWidget)
        self.label_name_.setGeometry(QtCore.QRect(220, 20, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name_.setFont(font)
        self.label_name_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_.setObjectName("label_name_")
        self.label_age_ = QtWidgets.QLabel(self.formWidget)
        self.label_age_.setGeometry(QtCore.QRect(220, 80, 160, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_age_.setFont(font)
        self.label_age_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_age_.setObjectName("label_age_")
        self.label_weight_ = QtWidgets.QLabel(self.formWidget)
        self.label_weight_.setGeometry(QtCore.QRect(220, 140, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_weight_.setFont(font)
        self.label_weight_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_weight_.setObjectName("label_weight_")
        self.label_boy_ = QtWidgets.QLabel(self.formWidget)
        self.label_boy_.setGeometry(QtCore.QRect(220, 200, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_boy_.setFont(font)
        self.label_boy_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_boy_.setObjectName("label_boy_")
        self.label_kitle_indeks_ = QtWidgets.QLabel(self.formWidget)
        self.label_kitle_indeks_.setGeometry(QtCore.QRect(220, 320, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kitle_indeks_.setFont(font)
        self.label_kitle_indeks_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kitle_indeks_.setObjectName("label_kitle_indeks_")
        self.label_kalori_ihtiyac_ = QtWidgets.QLabel(self.formWidget)
        self.label_kalori_ihtiyac_.setGeometry(QtCore.QRect(220, 380, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kalori_ihtiyac_.setFont(font)
        self.label_kalori_ihtiyac_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kalori_ihtiyac_.setObjectName("label_kalori_ihtiyac_")
        self.label_cinsiyet = QtWidgets.QLabel(self.formWidget)
        self.label_cinsiyet.setGeometry(QtCore.QRect(10, 260, 160, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_cinsiyet.setFont(font)
        self.label_cinsiyet.setObjectName("label_cinsiyet")
        self.label_cinsiyet_ = QtWidgets.QLabel(self.formWidget)
        self.label_cinsiyet_.setGeometry(QtCore.QRect(220, 260, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cinsiyet_.setFont(font)
        self.label_cinsiyet_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cinsiyet_.setObjectName("label_cinsiyet_")
        self.label_cinsiyet_image = QtWidgets.QLabel(self)
        self.label_cinsiyet_image.setGeometry(QtCore.QRect(0, 0, 141, 121))
        self.label_cinsiyet_image.setStyleSheet("image: url(:/icons/icons/Man.ico);")
        self.label_cinsiyet_image.setText("")
        self.label_cinsiyet_image.setObjectName("label_cinsiyet_image")
        self.comboBox_profiller = QtWidgets.QComboBox(self)
        self.comboBox_profiller.setGeometry(QtCore.QRect(400, 70, 201, 30))
        self.comboBox_profiller.setStyleSheet("background-color: rgb(48,123,172);")
        self.comboBox_profiller.setObjectName("comboBox_profiller")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_profiller.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(self)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(390, 190, 211, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_update = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/profil_guncelle.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_update.setIcon(icon3)
        self.pushButton_update.setIconSize(QtCore.QSize(84, 84))
        self.pushButton_update.setToolTip("Seçili profili güncelle")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/profil_ekle.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon1)
        self.pushButton_add.setIconSize(QtCore.QSize(84, 84))
        self.pushButton_add.setToolTip("Yeni profil ekle")
        self.pushButton_update.setObjectName("pushButton_guncelle")
        self.verticalLayout_2.addWidget(self.pushButton_update)
        self.pushButton_delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/profil_sil.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon2)
        self.pushButton_delete.setIconSize(QtCore.QSize(84, 84))
        self.pushButton_delete.setToolTip("Seçili profili sil")
        self.pushButton_delete.setObjectName("pushButton_sil")
        self.verticalLayout_2.addWidget(self.pushButton_delete)
        self.label_profil_secin = QtWidgets.QLabel(self)
        self.label_profil_secin.setGeometry(QtCore.QRect(400, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_profil_secin.setFont(font)
        self.label_profil_secin.setStyleSheet("background-color: rgb(48,123,172);\n""")
        self.label_profil_secin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_profil_secin.setObjectName("label_profil_secin")
#################################################################################################################
        self.update_profile = updateProfile()
        self.profil_ekle = Profile()

        # signaller
        self.profil_ekle.new_user_signal.connect(self.add_new_profile)
        self.update_profile.new_user_signal.connect(self.profil_guncelle)
        self.pushButton_add.clicked.connect(self.open_new_window)
        self.comboBox_profiller.currentIndexChanged['int'].connect(self.comboBox_index_change)
        self.pushButton_update.clicked.connect(self.open_update_page)
        self.pushButton_delete.clicked.connect(self.profil_delete)


        return self

    @QtCore.pyqtSlot(list)
    def add_new_profile(self, profile):
        """yeni profil,profil listesine eklenir"""
        self.profiles.append(profile)
        self.comboBox_profiller.addItem(profile[0])
        self.profil_ekle.clear()
        self.profil_ekle.close()
        self.comboBox_index_change()

    @QtCore.pyqtSlot()
    def open_new_window(self):
        """profil ekleme penceresi açılır"""
        self.profil_ekle.show()

    @QtCore.pyqtSlot()
    def comboBox_index_change(self):
        """profil değiştirirsek çalışır"""
        if self.profiles:
            select_profile = self.comboBox_profiller.currentIndex()
            # print(select_profile)
            # print(self.profiles)
            if self.profiles[select_profile]:
                isim, yas, kilo, boy, cinsiyet = self.profiles[select_profile]

                self.label_name_.setText(isim)
                self.label_age_.setText(yas)
                self.label_weight_.setText(kilo)
                self.label_boy_.setText(boy)
                self.label_cinsiyet_.setText(cinsiyet)

                if cinsiyet == "Erkek":
                    self.label_cinsiyet_image.setStyleSheet("image: url(:/icons/icons/Man.ico);")
                else:
                    self.label_cinsiyet_image.setStyleSheet("image: url(:/icons/icons/Woman.png);")

                kalori_ihtiyac = self.profil_ekle.gunlukKaloriIhtiyaciHesapla(kilo, cinsiyet)

                self.label_kalori_ihtiyac_.setText(str(kalori_ihtiyac))
                vki = self.profil_ekle.vkiHesapla(boy, kilo)
                self.label_kitle_indeks_.setText(str(vki))
        else:
            self.label_name_.clear()
            self.label_age_.clear()
            self.label_weight_.clear()
            self.label_boy_.clear()
            self.label_cinsiyet_.clear()
            self.label_kitle_indeks_.clear()
            self.label_kalori_ihtiyac_.clear()
            self.label_cinsiyet_image.setStyleSheet("")


    @QtCore.pyqtSlot()
    def open_update_page(self):
        if self.profiles:
            secilen = self.comboBox_profiller.currentIndex()
            profil = self.profiles[secilen]
            self.update_profile.ui.lineEdit_guncelle_name.setText(profil[0])
            self.update_profile.ui.lineEdit_guncelle_age.setText(profil[1])
            self.update_profile.ui.lineEdit_guncelle_weight.setText(profil[2])
            self.update_profile.ui.lineEdit_guncelle_boy.setText(profil[3])
            self.update_profile.ui.comboBox_guncelle_cinsiyet.addItem(profil[4])
            self.update_profile.show()

    @QtCore.pyqtSlot(list)
    def profil_guncelle(self, profil):
        secilen = self.comboBox_profiller.currentIndex()
        self.profiles[secilen] = profil
        self.update_profile.clear()
        self.update_profile.close()
        self.comboBox_index_change()

    @QtCore.pyqtSlot()
    def profil_delete(self):
        if self.profiles:
            index = self.comboBox_profiller.currentIndex()
            self.comboBox_profiller.removeItem(index)
            profil = self.profiles[index]
            self.profiles.remove(profil)
            if self.profiles != []:
                self.comboBox_profiller.setCurrentIndex(0)
            self.comboBox_index_change()

    def retranslate(self):
        _translate = QtCore.QCoreApplication.translate

        self.label_name.setText(_translate("main", "Kullanıcı İsmi"))
        self.label_age.setText(_translate("main", "Kullanıcı Yaşı"))
        self.label_kitle_indeks.setText(_translate("main", "Vücut Kitle İndeksi"))
        self.label_kalori_ihtiyac.setText(_translate("main", "Günlük Kalori İhtiyacı(kal)"))
        self.label_weight.setText(_translate("main", "Kullanıcı Kilosu(kg)"))
        self.label_boy.setText(_translate("main", "Kullanıcı Boyu(m)"))
        self.label_cinsiyet.setText(_translate("main", "Kullanıcı Cinsiyeti"))
        self.label_profil_secin.setText(_translate("main", "Profil Seçin"))